apiVersion: v1
kind: Service
metadata:
  name: user-register-service
spec:
  type: NodePort
  selector:
    type: poc
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 32001
  
---
apiVersion: v1
kind: Service
metadata:
  name: user-login-service
spec:
  type: NodePort
  selector:
    type: poc
  ports:
    - port: 3002
      targetPort: 3002
      nodePort: 32002
  

---
apiVersion: v1
kind: Service
metadata:
  name: user-create-service
spec:
  type: NodePort
  selector:
    type: poc
  ports:
    - port: 3003
      targetPort: 3003
      nodePort: 32003
  

---
apiVersion: v1
kind: Service
metadata:
  name: user-view-service
spec:
  type: NodePort
  selector:
    type: poc
  ports:
    - port: 3004
      targetPort: 3004
      nodePort: 32004

